version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for JS
  - package-ecosystem: "npm"
    directory: "/open-social-frontend"
    schedule:
      interval: "daily"
  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/open-social"
    schedule:
      interval: "daily"
  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "daily"
