AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  open-social

  open-social SAM Infrastructure

Globals:
  Function:
    Timeout: 5

Resources:
  OpenSocialCoreLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: open_social_core
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

  ProjectScrapperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: project_scrapper/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 300
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: "github/open-social-token"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:eu-west-1:326499071401:secret:mongodb-uri-qYViNv"
      Layers:
        - Ref: OpenSocialCoreLayer
      Events:
        ScrapeHumanitarianEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 4 * * ? *)'
            Input: "{\"topic\": \"humanitarian\"}"
        ScrapeNonProfitEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(10 4 * * ? *)'
            Input: "{\"topic\": \"non-profit\"}"
        ScrapeSocialJusticeEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(20 4 * * ? *)'
            Input: "{\"topic\": \"social justice\"}"
        ScrapeSocialChangeEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(30 4 * * ? *)'
            Input: "{\"topic\": \"social change\"}"
        ScrapeClimateChangeEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(40 4 * * ? *)'
            Input: "{\"topic\": \"climate change\"}"
        ScrapePovertyEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(50 4 * * ? *)'
            Input: "{\"topic\": \"poverty\"}"
        ScrapePartpDemocracyEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 5 * * ? *)'
            Input: "{\"topic\": \"participatory democracy\"}"
        ScrapeFeminismEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(10 5 * * ? *)'
            Input: "{\"topic\": \"feminism\"}"

  ApiCrudLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: open_social_crud/
      Handler: app.entrypoint
      Runtime: python3.12
      MemorySize: 1024
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: "arn:aws:secretsmanager:eu-west-1:326499071401:secret:mongodb-uri-qYViNv"
      Layers:
        - Ref: OpenSocialCoreLayer
      Events:
        ListProjects:
          Type: Api
          Properties:
            Path: /projects
            Method: get
            RestApiId:
              Ref: OpenSocialAPI
        ListTopics:
          Type: Api
          Properties:
            Path: /topics
            Method: get
            RestApiId:
              Ref: OpenSocialAPI
        ListLanguages:
          Type: Api
          Properties:
            Path: /languages
            Method: get
            RestApiId:
              Ref: OpenSocialAPI
        SearchProjects:
          Type: Api
          Properties:
            Path: /search
            Method: get
            RestApiId:
              Ref: OpenSocialAPI

  OpenSocialAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      MinimumCompressionSize: 0
      BinaryMediaTypes:
        - application~1json
      Cors:
        AllowMethods: "'GET'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "'*'"
      Domain:
        DomainName: api.open-social.net
        CertificateArn: "arn:aws:acm:eu-west-1:326499071401:certificate/1a61d95d-8740-4334-b641-8c0b7c429c46"
        Route53:
          HostedZoneId: Z056117665GXDL3UXFF7


Outputs:
  ProjectScrapperFunction:
    Description: "Github Project Scrapper"
    Value: !GetAtt ProjectScrapperFunction.Arn
  ProjectScrapperFunctionIamRole:
    Description: "Implicit IAM Role created for Project Scrapper function"
    Value: !GetAtt ProjectScrapperFunction.Arn
