AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  open-social

  Sample SAM Template for open-social

Globals:
  Function:
    Timeout: 3

Resources:
  OpenSocialCoreLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: open_social_core
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8

  ProjectScrapperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: project_scrapper/
      Handler: app.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectDynamoDBTable
      Layers:
        - Ref: OpenSocialCoreLayer

  ApiCrudLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: open_social_crud/
      Handler: app.list_projects
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectDynamoDBTable
      Layers:
        - Ref: OpenSocialCoreLayer
      Events:
        ListEvent:
          Type: Api
          Properties:
            Path: /projects
            Method: get
            RestApiId:
              Ref: OpenSocialAPI

  ProjectDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: 'full_name'
        Type: String
      TableName: open-social-projects
      ProvisionedThroughput:
        ReadCapacityUnits: 25
        WriteCapacityUnits: 25

  OpenSocialAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
      MinimumCompressionSize: 0
      Cors:
        AllowMethods: "'GET'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "'*'"


Outputs:
  ProjectScrapperFunction:
    Description: "Github Project Scrapper"
    Value: !GetAtt ProjectScrapperFunction.Arn
  ProjectScrapperFunctionIamRole:
    Description: "Implicit IAM Role created for Project Scrapper function"
    Value: !GetAtt ProjectScrapperFunction.Arn
