PROJECT_LIST_RESPONSE = '''
{
    "total_count": 2,
    "incomplete_results": false,
    "items": [
        {
            "id": 11636397,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMTYzNjM5Nw==",
            "name": "crisischeckin",
            "full_name": "HTBox/crisischeckin",
            "private": false,
            "owner": {
                "login": "HTBox",
                "id": 5184596,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjUxODQ1OTY=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/5184596?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/HTBox",
                "html_url": "https://github.com/HTBox",
                "followers_url": "https://api.github.com/users/HTBox/followers",
                "following_url": "https://api.github.com/users/HTBox/following{/other_user}",
                "gists_url": "https://api.github.com/users/HTBox/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/HTBox/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/HTBox/subscriptions",
                "organizations_url": "https://api.github.com/users/HTBox/orgs",
                "repos_url": "https://api.github.com/users/HTBox/repos",
                "events_url": "https://api.github.com/users/HTBox/events{/privacy}",
                "received_events_url": "https://api.github.com/users/HTBox/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/HTBox/crisischeckin",
            "description": "Crisischeckin Humanitarian Toolbox repository",
            "fork": false,
            "url": "https://api.github.com/repos/HTBox/crisischeckin",
            "forks_url": "https://api.github.com/repos/HTBox/crisischeckin/forks",
            "keys_url": "https://api.github.com/repos/HTBox/crisischeckin/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/HTBox/crisischeckin/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/HTBox/crisischeckin/teams",
            "hooks_url": "https://api.github.com/repos/HTBox/crisischeckin/hooks",
            "issue_events_url": "https://api.github.com/repos/HTBox/crisischeckin/issues/events{/number}",
            "events_url": "https://api.github.com/repos/HTBox/crisischeckin/events",
            "assignees_url": "https://api.github.com/repos/HTBox/crisischeckin/assignees{/user}",
            "branches_url": "https://api.github.com/repos/HTBox/crisischeckin/branches{/branch}",
            "tags_url": "https://api.github.com/repos/HTBox/crisischeckin/tags",
            "blobs_url": "https://api.github.com/repos/HTBox/crisischeckin/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/HTBox/crisischeckin/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/HTBox/crisischeckin/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/HTBox/crisischeckin/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/HTBox/crisischeckin/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/HTBox/crisischeckin/languages",
            "stargazers_url": "https://api.github.com/repos/HTBox/crisischeckin/stargazers",
            "contributors_url": "https://api.github.com/repos/HTBox/crisischeckin/contributors",
            "subscribers_url": "https://api.github.com/repos/HTBox/crisischeckin/subscribers",
            "subscription_url": "https://api.github.com/repos/HTBox/crisischeckin/subscription",
            "commits_url": "https://api.github.com/repos/HTBox/crisischeckin/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/HTBox/crisischeckin/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/HTBox/crisischeckin/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/HTBox/crisischeckin/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/HTBox/crisischeckin/contents/{+path}",
            "compare_url": "https://api.github.com/repos/HTBox/crisischeckin/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/HTBox/crisischeckin/merges",
            "archive_url": "https://api.github.com/repos/HTBox/crisischeckin/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/HTBox/crisischeckin/downloads",
            "issues_url": "https://api.github.com/repos/HTBox/crisischeckin/issues{/number}",
            "pulls_url": "https://api.github.com/repos/HTBox/crisischeckin/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/HTBox/crisischeckin/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/HTBox/crisischeckin/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/HTBox/crisischeckin/labels{/name}",
            "releases_url": "https://api.github.com/repos/HTBox/crisischeckin/releases{/id}",
            "deployments_url": "https://api.github.com/repos/HTBox/crisischeckin/deployments",
            "created_at": "2013-07-24T14:14:46Z",
            "updated_at": "2020-10-07T23:08:23Z",
            "pushed_at": "2018-10-24T18:49:51Z",
            "git_url": "git://github.com/HTBox/crisischeckin.git",
            "ssh_url": "git@github.com:HTBox/crisischeckin.git",
            "clone_url": "https://github.com/HTBox/crisischeckin.git",
            "svn_url": "https://github.com/HTBox/crisischeckin",
            "homepage": "",
            "size": 79853,
            "stargazers_count": 177,
            "watchers_count": 177,
            "language": "C#",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 172,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 258,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI="
            },
            "forks": 172,
            "open_issues": 258,
            "watchers": 177,
            "default_branch": "master",
            "score": 1
        },
        {
            "id": 14497749,
            "node_id": "MDEwOlJlcG9zaXRvcnkxNDQ5Nzc0OQ==",
            "name": "kobocat",
            "full_name": "kobotoolbox/kobocat",
            "private": false,
            "owner": {
                "login": "kobotoolbox",
                "id": 5543677,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU1NDM2Nzc=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/5543677?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/kobotoolbox",
                "html_url": "https://github.com/kobotoolbox",
                "followers_url": "https://api.github.com/users/kobotoolbox/followers",
                "following_url": "https://api.github.com/users/kobotoolbox/following{/other_user}",
                "gists_url": "https://api.github.com/users/kobotoolbox/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/kobotoolbox/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kobotoolbox/subscriptions",
                "organizations_url": "https://api.github.com/users/kobotoolbox/orgs",
                "repos_url": "https://api.github.com/users/kobotoolbox/repos",
                "events_url": "https://api.github.com/users/kobotoolbox/events{/privacy}",
                "received_events_url": "https://api.github.com/users/kobotoolbox/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/kobotoolbox/kobocat",
            "description": "Data collection for humanitarian emergencies",
            "fork": false,
            "url": "https://api.github.com/repos/kobotoolbox/kobocat",
            "forks_url": "https://api.github.com/repos/kobotoolbox/kobocat/forks",
            "keys_url": "https://api.github.com/repos/kobotoolbox/kobocat/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/kobotoolbox/kobocat/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/kobotoolbox/kobocat/teams",
            "hooks_url": "https://api.github.com/repos/kobotoolbox/kobocat/hooks",
            "issue_events_url": "https://api.github.com/repos/kobotoolbox/kobocat/issues/events{/number}",
            "events_url": "https://api.github.com/repos/kobotoolbox/kobocat/events",
            "assignees_url": "https://api.github.com/repos/kobotoolbox/kobocat/assignees{/user}",
            "branches_url": "https://api.github.com/repos/kobotoolbox/kobocat/branches{/branch}",
            "tags_url": "https://api.github.com/repos/kobotoolbox/kobocat/tags",
            "blobs_url": "https://api.github.com/repos/kobotoolbox/kobocat/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/kobotoolbox/kobocat/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/kobotoolbox/kobocat/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/kobotoolbox/kobocat/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/kobotoolbox/kobocat/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/kobotoolbox/kobocat/languages",
            "stargazers_url": "https://api.github.com/repos/kobotoolbox/kobocat/stargazers",
            "contributors_url": "https://api.github.com/repos/kobotoolbox/kobocat/contributors",
            "subscribers_url": "https://api.github.com/repos/kobotoolbox/kobocat/subscribers",
            "subscription_url": "https://api.github.com/repos/kobotoolbox/kobocat/subscription",
            "commits_url": "https://api.github.com/repos/kobotoolbox/kobocat/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/kobotoolbox/kobocat/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/kobotoolbox/kobocat/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/kobotoolbox/kobocat/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/kobotoolbox/kobocat/contents/{+path}",
            "compare_url": "https://api.github.com/repos/kobotoolbox/kobocat/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/kobotoolbox/kobocat/merges",
            "archive_url": "https://api.github.com/repos/kobotoolbox/kobocat/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/kobotoolbox/kobocat/downloads",
            "issues_url": "https://api.github.com/repos/kobotoolbox/kobocat/issues{/number}",
            "pulls_url": "https://api.github.com/repos/kobotoolbox/kobocat/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/kobotoolbox/kobocat/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/kobotoolbox/kobocat/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/kobotoolbox/kobocat/labels{/name}",
            "releases_url": "https://api.github.com/repos/kobotoolbox/kobocat/releases{/id}",
            "deployments_url": "https://api.github.com/repos/kobotoolbox/kobocat/deployments",
            "created_at": "2013-11-18T16:16:32Z",
            "updated_at": "2020-11-23T14:04:04Z",
            "pushed_at": "2020-06-23T14:04:02Z",
            "git_url": "git://github.com/kobotoolbox/kobocat.git",
            "ssh_url": "git@github.com:kobotoolbox/kobocat.git",
            "clone_url": "https://github.com/kobotoolbox/kobocat.git",
            "svn_url": "https://github.com/kobotoolbox/kobocat",
            "homepage": "kobotoolbox.org",
            "size": 23074,
            "stargazers_count": 77,
            "watchers_count": 77,
            "language": "Python",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 84,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 145,
            "license": {
                "key": "bsd-2-clause",
                "name": "BSD 2-Clause Simplified License",
                "spdx_id": "BSD-2-Clause",
                "url": "https://api.github.com/licenses/bsd-2-clause",
                "node_id": "MDc6TGljZW5zZTQ="
            },
            "forks": 84,
            "open_issues": 145,
            "watchers": 77,
            "default_branch": "master",
            "score": 1
        }
    ]
}
'''

OUTDATED_PROJECT_LIST_RESPONSE = '''
{
    "total_count": 2,
    "incomplete_results": false,
    "items": [
        {
            "id": 11636397,
            "node_id": "MDEwOlJlcG9zaXRvcnkxMTYzNjM5Nw==",
            "name": "crisischeckin",
            "full_name": "HTBox/crisischeckin",
            "private": false,
            "owner": {
                "login": "HTBox",
                "id": 5184596,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjUxODQ1OTY=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/5184596?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/HTBox",
                "html_url": "https://github.com/HTBox",
                "followers_url": "https://api.github.com/users/HTBox/followers",
                "following_url": "https://api.github.com/users/HTBox/following{/other_user}",
                "gists_url": "https://api.github.com/users/HTBox/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/HTBox/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/HTBox/subscriptions",
                "organizations_url": "https://api.github.com/users/HTBox/orgs",
                "repos_url": "https://api.github.com/users/HTBox/repos",
                "events_url": "https://api.github.com/users/HTBox/events{/privacy}",
                "received_events_url": "https://api.github.com/users/HTBox/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/HTBox/crisischeckin",
            "description": "Crisischeckin Humanitarian Toolbox repository",
            "fork": false,
            "url": "https://api.github.com/repos/HTBox/crisischeckin",
            "forks_url": "https://api.github.com/repos/HTBox/crisischeckin/forks",
            "keys_url": "https://api.github.com/repos/HTBox/crisischeckin/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/HTBox/crisischeckin/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/HTBox/crisischeckin/teams",
            "hooks_url": "https://api.github.com/repos/HTBox/crisischeckin/hooks",
            "issue_events_url": "https://api.github.com/repos/HTBox/crisischeckin/issues/events{/number}",
            "events_url": "https://api.github.com/repos/HTBox/crisischeckin/events",
            "assignees_url": "https://api.github.com/repos/HTBox/crisischeckin/assignees{/user}",
            "branches_url": "https://api.github.com/repos/HTBox/crisischeckin/branches{/branch}",
            "tags_url": "https://api.github.com/repos/HTBox/crisischeckin/tags",
            "blobs_url": "https://api.github.com/repos/HTBox/crisischeckin/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/HTBox/crisischeckin/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/HTBox/crisischeckin/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/HTBox/crisischeckin/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/HTBox/crisischeckin/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/HTBox/crisischeckin/languages",
            "stargazers_url": "https://api.github.com/repos/HTBox/crisischeckin/stargazers",
            "contributors_url": "https://api.github.com/repos/HTBox/crisischeckin/contributors",
            "subscribers_url": "https://api.github.com/repos/HTBox/crisischeckin/subscribers",
            "subscription_url": "https://api.github.com/repos/HTBox/crisischeckin/subscription",
            "commits_url": "https://api.github.com/repos/HTBox/crisischeckin/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/HTBox/crisischeckin/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/HTBox/crisischeckin/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/HTBox/crisischeckin/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/HTBox/crisischeckin/contents/{+path}",
            "compare_url": "https://api.github.com/repos/HTBox/crisischeckin/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/HTBox/crisischeckin/merges",
            "archive_url": "https://api.github.com/repos/HTBox/crisischeckin/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/HTBox/crisischeckin/downloads",
            "issues_url": "https://api.github.com/repos/HTBox/crisischeckin/issues{/number}",
            "pulls_url": "https://api.github.com/repos/HTBox/crisischeckin/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/HTBox/crisischeckin/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/HTBox/crisischeckin/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/HTBox/crisischeckin/labels{/name}",
            "releases_url": "https://api.github.com/repos/HTBox/crisischeckin/releases{/id}",
            "deployments_url": "https://api.github.com/repos/HTBox/crisischeckin/deployments",
            "created_at": "2013-07-24T14:14:46Z",
            "updated_at": "2020-10-07T23:08:23Z",
            "pushed_at": "2018-10-24T18:49:51Z",
            "git_url": "git://github.com/HTBox/crisischeckin.git",
            "ssh_url": "git@github.com:HTBox/crisischeckin.git",
            "clone_url": "https://github.com/HTBox/crisischeckin.git",
            "svn_url": "https://github.com/HTBox/crisischeckin",
            "homepage": "",
            "size": 79853,
            "stargazers_count": 177,
            "watchers_count": 177,
            "language": "C#",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 172,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 258,
            "license": {
                "key": "apache-2.0",
                "name": "Apache License 2.0",
                "spdx_id": "Apache-2.0",
                "url": "https://api.github.com/licenses/apache-2.0",
                "node_id": "MDc6TGljZW5zZTI="
            },
            "forks": 172,
            "open_issues": 258,
            "watchers": 177,
            "default_branch": "master",
            "score": 1
        },
        {
            "id": 14497749,
            "node_id": "MDEwOlJlcG9zaXRvcnkxNDQ5Nzc0OQ==",
            "name": "kobocat",
            "full_name": "kobotoolbox/kobocat",
            "private": false,
            "owner": {
                "login": "kobotoolbox",
                "id": 5543677,
                "node_id": "MDEyOk9yZ2FuaXphdGlvbjU1NDM2Nzc=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/5543677?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/kobotoolbox",
                "html_url": "https://github.com/kobotoolbox",
                "followers_url": "https://api.github.com/users/kobotoolbox/followers",
                "following_url": "https://api.github.com/users/kobotoolbox/following{/other_user}",
                "gists_url": "https://api.github.com/users/kobotoolbox/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/kobotoolbox/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kobotoolbox/subscriptions",
                "organizations_url": "https://api.github.com/users/kobotoolbox/orgs",
                "repos_url": "https://api.github.com/users/kobotoolbox/repos",
                "events_url": "https://api.github.com/users/kobotoolbox/events{/privacy}",
                "received_events_url": "https://api.github.com/users/kobotoolbox/received_events",
                "type": "Organization",
                "site_admin": false
            },
            "html_url": "https://github.com/kobotoolbox/kobocat",
            "description": "Data collection for humanitarian emergencies",
            "fork": false,
            "url": "https://api.github.com/repos/kobotoolbox/kobocat",
            "forks_url": "https://api.github.com/repos/kobotoolbox/kobocat/forks",
            "keys_url": "https://api.github.com/repos/kobotoolbox/kobocat/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/kobotoolbox/kobocat/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/kobotoolbox/kobocat/teams",
            "hooks_url": "https://api.github.com/repos/kobotoolbox/kobocat/hooks",
            "issue_events_url": "https://api.github.com/repos/kobotoolbox/kobocat/issues/events{/number}",
            "events_url": "https://api.github.com/repos/kobotoolbox/kobocat/events",
            "assignees_url": "https://api.github.com/repos/kobotoolbox/kobocat/assignees{/user}",
            "branches_url": "https://api.github.com/repos/kobotoolbox/kobocat/branches{/branch}",
            "tags_url": "https://api.github.com/repos/kobotoolbox/kobocat/tags",
            "blobs_url": "https://api.github.com/repos/kobotoolbox/kobocat/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/kobotoolbox/kobocat/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/kobotoolbox/kobocat/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/kobotoolbox/kobocat/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/kobotoolbox/kobocat/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/kobotoolbox/kobocat/languages",
            "stargazers_url": "https://api.github.com/repos/kobotoolbox/kobocat/stargazers",
            "contributors_url": "https://api.github.com/repos/kobotoolbox/kobocat/contributors",
            "subscribers_url": "https://api.github.com/repos/kobotoolbox/kobocat/subscribers",
            "subscription_url": "https://api.github.com/repos/kobotoolbox/kobocat/subscription",
            "commits_url": "https://api.github.com/repos/kobotoolbox/kobocat/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/kobotoolbox/kobocat/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/kobotoolbox/kobocat/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/kobotoolbox/kobocat/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/kobotoolbox/kobocat/contents/{+path}",
            "compare_url": "https://api.github.com/repos/kobotoolbox/kobocat/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/kobotoolbox/kobocat/merges",
            "archive_url": "https://api.github.com/repos/kobotoolbox/kobocat/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/kobotoolbox/kobocat/downloads",
            "issues_url": "https://api.github.com/repos/kobotoolbox/kobocat/issues{/number}",
            "pulls_url": "https://api.github.com/repos/kobotoolbox/kobocat/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/kobotoolbox/kobocat/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/kobotoolbox/kobocat/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/kobotoolbox/kobocat/labels{/name}",
            "releases_url": "https://api.github.com/repos/kobotoolbox/kobocat/releases{/id}",
            "deployments_url": "https://api.github.com/repos/kobotoolbox/kobocat/deployments",
            "created_at": "2013-11-18T16:16:32Z",
            "updated_at": "2015-11-23T14:04:04Z",
            "pushed_at": "2020-06-23T14:04:02Z",
            "git_url": "git://github.com/kobotoolbox/kobocat.git",
            "ssh_url": "git@github.com:kobotoolbox/kobocat.git",
            "clone_url": "https://github.com/kobotoolbox/kobocat.git",
            "svn_url": "https://github.com/kobotoolbox/kobocat",
            "homepage": "kobotoolbox.org",
            "size": 23074,
            "stargazers_count": 77,
            "watchers_count": 77,
            "language": "Python",
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 84,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 145,
            "license": {
                "key": "bsd-2-clause",
                "name": "BSD 2-Clause Simplified License",
                "spdx_id": "BSD-2-Clause",
                "url": "https://api.github.com/licenses/bsd-2-clause",
                "node_id": "MDc6TGljZW5zZTQ="
            },
            "forks": 84,
            "open_issues": 145,
            "watchers": 77,
            "default_branch": "master",
            "score": 1
        }
    ]
}
'''


CONTRIBUTORS = '''
[
    {
        "login": "Contributor",
        "id": 493969,
        "node_id": "MDQ6VXNlcjQ5Mzk2OQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/493969?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Contributor",
        "html_url": "https://github.com/Contributor",
        "followers_url": "https://api.github.com/users/Contributor/followers",
        "following_url": "https://api.github.com/users/Contributor/following{/other_user}",
        "gists_url": "https://api.github.com/users/Contributor/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Contributor/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Contributor/subscriptions",
        "organizations_url": "https://api.github.com/users/Contributor/orgs",
        "repos_url": "https://api.github.com/users/Contributor/repos",
        "events_url": "https://api.github.com/users/Contributor/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Contributor/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 184
    }
]
'''


SAMPLE_COMMITS = r''' 
[
    {
        "sha": "52774dbad84cf4e0c07e461321349f1ae294edfa",
        "node_id": "MDY6Q29tbWl0MTE2MzYzOTc6NTI3NzRkYmFkODRjZjRlMGMwN2U0NjEzMjEzNDlmMWFlMjk0ZWRmYQ==",
        "commit": {
            "author": {
                "name": "Tony Surma",
                "email": "tony@surmafamily.com",
                "date": "2017-04-22T14:14:23Z"
            },
            "committer": {
                "name": "GitHub",
                "email": "noreply@github.com",
                "date": "2017-04-22T14:14:23Z"
            },
            "message": "Merge pull request #702 from cmgutmanis/save-resources-from-home-page\n\nAdding mapping to resource object from homepage.",
            "tree": {
                "sha": "884ad1f7d828ef561e99f64eff1dc1655e2162dd",
                "url": "https://api.github.com/repos/HTBox/crisischeckin/git/trees/884ad1f7d828ef561e99f64eff1dc1655e2162dd"
            },
            "url": "https://api.github.com/repos/HTBox/crisischeckin/git/commits/52774dbad84cf4e0c07e461321349f1ae294edfa",
            "comment_count": 0,
            "verification": {
                "verified": false,
                "reason": "unsigned",
                "signature": null,
                "payload": null
            }
        },
        "url": "https://api.github.com/repos/HTBox/crisischeckin/commits/52774dbad84cf4e0c07e461321349f1ae294edfa",
        "html_url": "https://github.com/HTBox/crisischeckin/commit/52774dbad84cf4e0c07e461321349f1ae294edfa",
        "comments_url": "https://api.github.com/repos/HTBox/crisischeckin/commits/52774dbad84cf4e0c07e461321349f1ae294edfa/comments",
        "author": {
            "login": "tonysurma",
            "id": 5067595,
            "node_id": "MDQ6VXNlcjUwNjc1OTU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5067595?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/tonysurma",
            "html_url": "https://github.com/tonysurma",
            "followers_url": "https://api.github.com/users/tonysurma/followers",
            "following_url": "https://api.github.com/users/tonysurma/following{/other_user}",
            "gists_url": "https://api.github.com/users/tonysurma/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/tonysurma/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tonysurma/subscriptions",
            "organizations_url": "https://api.github.com/users/tonysurma/orgs",
            "repos_url": "https://api.github.com/users/tonysurma/repos",
            "events_url": "https://api.github.com/users/tonysurma/events{/privacy}",
            "received_events_url": "https://api.github.com/users/tonysurma/received_events",
            "type": "User",
            "site_admin": false
        },
        "committer": {
            "login": "web-flow",
            "id": 19864447,
            "node_id": "MDQ6VXNlcjE5ODY0NDQ3",
            "avatar_url": "https://avatars.githubusercontent.com/u/19864447?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/web-flow",
            "html_url": "https://github.com/web-flow",
            "followers_url": "https://api.github.com/users/web-flow/followers",
            "following_url": "https://api.github.com/users/web-flow/following{/other_user}",
            "gists_url": "https://api.github.com/users/web-flow/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/web-flow/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/web-flow/subscriptions",
            "organizations_url": "https://api.github.com/users/web-flow/orgs",
            "repos_url": "https://api.github.com/users/web-flow/repos",
            "events_url": "https://api.github.com/users/web-flow/events{/privacy}",
            "received_events_url": "https://api.github.com/users/web-flow/received_events",
            "type": "User",
            "site_admin": false
        },
        "parents": [
            {
                "sha": "2d837f280d4a6f474e17b400d12a32f6a5d71c37",
                "url": "https://api.github.com/repos/HTBox/crisischeckin/commits/2d837f280d4a6f474e17b400d12a32f6a5d71c37",
                "html_url": "https://github.com/HTBox/crisischeckin/commit/2d837f280d4a6f474e17b400d12a32f6a5d71c37"
            },
            {
                "sha": "7e072c470bb31b3a265ac53d0beb73f3e0856b7b",
                "url": "https://api.github.com/repos/HTBox/crisischeckin/commits/7e072c470bb31b3a265ac53d0beb73f3e0856b7b",
                "html_url": "https://github.com/HTBox/crisischeckin/commit/7e072c470bb31b3a265ac53d0beb73f3e0856b7b"
            }
        ]
    },
    {
        "sha": "2d837f280d4a6f474e17b400d12a32f6a5d71c37",
        "node_id": "MDY6Q29tbWl0MTE2MzYzOTc6MmQ4MzdmMjgwZDRhNmY0NzRlMTdiNDAwZDEyYTMyZjZhNWQ3MWMzNw==",
        "commit": {
            "author": {
                "name": "Tony Surma",
                "email": "tony@surmafamily.com",
                "date": "2017-04-22T14:13:56Z"
            },
            "committer": {
                "name": "GitHub",
                "email": "noreply@github.com",
                "date": "2017-04-22T14:13:56Z"
            },
            "message": "Merge pull request #706 from abhijeet2083/master\n\nfixed the issue where organization dropdown error not clearing on account registration page #704",
            "tree": {
                "sha": "cffb232e050a7dc6ca5a56415ab1370d0ebcb359",
                "url": "https://api.github.com/repos/HTBox/crisischeckin/git/trees/cffb232e050a7dc6ca5a56415ab1370d0ebcb359"
            },
            "url": "https://api.github.com/repos/HTBox/crisischeckin/git/commits/2d837f280d4a6f474e17b400d12a32f6a5d71c37",
            "comment_count": 0,
            "verification": {
                "verified": false,
                "reason": "unsigned",
                "signature": null,
                "payload": null
            }
        },
        "url": "https://api.github.com/repos/HTBox/crisischeckin/commits/2d837f280d4a6f474e17b400d12a32f6a5d71c37",
        "html_url": "https://github.com/HTBox/crisischeckin/commit/2d837f280d4a6f474e17b400d12a32f6a5d71c37",
        "comments_url": "https://api.github.com/repos/HTBox/crisischeckin/commits/2d837f280d4a6f474e17b400d12a32f6a5d71c37/comments",
        "author": {
            "login": "tonysurma",
            "id": 5067595,
            "node_id": "MDQ6VXNlcjUwNjc1OTU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5067595?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/tonysurma",
            "html_url": "https://github.com/tonysurma",
            "followers_url": "https://api.github.com/users/tonysurma/followers",
            "following_url": "https://api.github.com/users/tonysurma/following{/other_user}",
            "gists_url": "https://api.github.com/users/tonysurma/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/tonysurma/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tonysurma/subscriptions",
            "organizations_url": "https://api.github.com/users/tonysurma/orgs",
            "repos_url": "https://api.github.com/users/tonysurma/repos",
            "events_url": "https://api.github.com/users/tonysurma/events{/privacy}",
            "received_events_url": "https://api.github.com/users/tonysurma/received_events",
            "type": "User",
            "site_admin": false
        },
        "committer": {
            "login": "web-flow",
            "id": 19864447,
            "node_id": "MDQ6VXNlcjE5ODY0NDQ3",
            "avatar_url": "https://avatars.githubusercontent.com/u/19864447?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/web-flow",
            "html_url": "https://github.com/web-flow",
            "followers_url": "https://api.github.com/users/web-flow/followers",
            "following_url": "https://api.github.com/users/web-flow/following{/other_user}",
            "gists_url": "https://api.github.com/users/web-flow/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/web-flow/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/web-flow/subscriptions",
            "organizations_url": "https://api.github.com/users/web-flow/orgs",
            "repos_url": "https://api.github.com/users/web-flow/repos",
            "events_url": "https://api.github.com/users/web-flow/events{/privacy}",
            "received_events_url": "https://api.github.com/users/web-flow/received_events",
            "type": "User",
            "site_admin": false
        },
        "parents": [
            {
                "sha": "df644d98f0dc4c415d47a18b890790514063bfa3",
                "url": "https://api.github.com/repos/HTBox/crisischeckin/commits/df644d98f0dc4c415d47a18b890790514063bfa3",
                "html_url": "https://github.com/HTBox/crisischeckin/commit/df644d98f0dc4c415d47a18b890790514063bfa3"
            },
            {
                "sha": "bcfdd5dd425840ced4f775d7318fd5332628c901",
                "url": "https://api.github.com/repos/HTBox/crisischeckin/commits/bcfdd5dd425840ced4f775d7318fd5332628c901",
                "html_url": "https://github.com/HTBox/crisischeckin/commit/bcfdd5dd425840ced4f775d7318fd5332628c901"
            }
        ]
    }
]
'''

SAMPLE_HEADER = {
    'link': '<https://api.github.com/search/repositories?q=fake_query&sort=updated&per_page=50&page=2>; rel="next", <https://api.github.com/search/repositories?q=fake_query&sort=updated&per_page=50&page=16>; rel="last"'  # noqa
}
