name: 'DependaBot Pull Requests'

on:
  pull_request:
    branches:
      - master

jobs:
  run_backend_tests:
    name: 'Run Backend Tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Cache dependencies'
        uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 'Install Pip Dependencies'
        run: pip install -r open-social/tests/test_requirements.txt

      - name: 'Run Unittests'
        working-directory: ./open-social
        run: |
          pytest
        env:
          AWS_DEFAULT_REGION: 'eu-central-1'

  run_frontend_tests:
    name: 'Run Frontend Tests'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./open-social-front-v2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Configure Node'
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 'Node Cache'
        uses: actions/cache@v3.3.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Run Unit Tests'
        run: npm run test-ci
