name: 'Open Social Deploy'
on:
  push:
    branches:
      - master

jobs:
  sam-app:
    name: 'SAM App Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: 'Install Pip Dependencies'
        run: pip install -r open-social/tests/test_requirements.txt

      - name: 'Run Unittests'
        run: |
          pytest -v open-social/tests
