name: 'Open Social Deploy'
on:
  push:
    branches:
      - master

jobs:
  sam-app-docker:
    name: 'Sam App Build Docker Image'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./actions/aws-sam
          file: ./actions/aws-sam/Dockerfile.build
          push: true
          platforms: linux/amd64
          cache-to: type=inline
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/aws-sam-action:latest
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aws-sam-action:latest

  sam-app:
    name: 'SAM App Deploy'
    runs-on: ubuntu-latest
    needs: ['sam-app-docker', 'infrastructure']

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Cache dependencies'
        uses: actions/cache@v2.1.5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 'Setup Python'
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'

      - name: 'Install Pip Dependencies'
        run: pip install -r open-social/tests/test_requirements.txt

      - name: 'Run Unittests'
        working-directory: ./open-social
        run: |
          pytest
        env:
          AWS_DEFAULT_REGION: 'eu-central-1'

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Validate SAM App'
        uses: ./actions/aws-sam
        with:
          sam_command: validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: 'Build SAM App'
        uses: ./actions/aws-sam
        with:
          sam_command: build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: 'Deploy SAM App'
        uses: ./actions/aws-sam
        with:
          sam_command: deploy --template-file .aws-sam/build/template.yaml --stack-name open-social --capabilities CAPABILITY_NAMED_IAM --s3-bucket open-social-sam-layers --no-fail-on-empty-changeset
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

  infrastructure:
    name: 'Basic Infrastructure'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 'Manually zip lambda file'
        run: zip index.zip index.py
        working-directory: /home/runner/work/opensocial/opensocial/infrastructure/lambda_files/

      - name: 'Configure Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.29

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Format'
        run: terraform fmt -check -diff

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve

  static-host:
    name: 'Build Frontend'
    runs-on: ubuntu-latest
    needs: ['sam-app']
    defaults:
      run:
        working-directory: ./open-social-frontend

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 'Configure Node'
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - name: 'Node Cache'
        uses: actions/cache@v2.1.5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Install Gatsby S3 Plugin'
        run: npm install gatsby-plugin-s3

      - name: 'Run Unit Tests'
        run: npm test

      - name: 'Run e2e Tests'
        run: npm run test:e2e:ci

      - name: 'Clean before build'
        run: npm run clean

      - name: 'Build App'
        run: npm run build

      - name: 'Deploy App'
        run: npm run deploy
