name: 'Open Social Infra'
on:
  - push
jobs:
  terraform:
    name: 'Infra'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.24
      - name: 'Terraform Init'
        run: terraform init
      - id: validate
        run: terraform validate
